// AUTO-GENERATED by scripts/fetch-wikipedia-excerpts.mjs — do not edit by hand.
// Re-run the script to refresh.  Sourced from Wikipedia (CC BY-SA 4.0).

export interface WikipediaExcerpt {
  title: string;
  extract: string;
  thumbnail?: string;
  url: string;
}

export const wikipediaExcerpts: Record<string, WikipediaExcerpt> = {
  "https://en.wikipedia.org/wiki/Antikythera_mechanism": {
    title: `Antikythera mechanism`,
    extract: `The Antikythera mechanism is an ancient Greek hand-powered orrery. It is the oldest known example of an analogue computer. It could be used to predict astronomical positions and eclipses decades in advance. It could also be used to track the four-year cycle of athletic games similar to an olympiad, the cycle of the ancient Olympic Games.`,
    thumbnail: `/images/330px-Antikythera_Fragment_A_(Front).webp.png`,
    url: `https://en.wikipedia.org/wiki/Antikythera_mechanism`,
  },
  "https://en.wikipedia.org/wiki/Mechanical_Turk": {
    title: `Mechanical Turk`,
    extract: `The Mechanical Turk, also known as the Automaton Chess Player or simply the Turk, was a chess-playing machine first displayed in 1770, which appeared to be able to play a strong game of chess autonomously, but whose pieces were in reality moved via levers and magnets by a chess master hidden in its lower cavity. The machine was toured and exhibited for 84 years as an automaton, and continued giving occasional exhibitions until 1854, when it was destroyed in a fire. In 1857, an article published by the owner's son provided the first full explanation of the mechanism, which had been widely suspected to be a hoax but never accurately described while the machine still existed.`,
    thumbnail: `/images/330px-Racknitz_-_The_Turk_3.jpg`,
    url: `https://en.wikipedia.org/wiki/Mechanical_Turk`,
  },
  "https://en.wikipedia.org/wiki/Pascal%27s_calculator": {
    title: `Pascaline`,
    extract: `The Pascaline is a mechanical calculator invented by Blaise Pascal in 1642. Pascal was led to develop a calculator by the laborious arithmetical calculations required by his father's work as the supervisor of taxes in Rouen, France. He designed the machine to add and subtract two numbers and to perform multiplication and division through repeated addition or subtraction.`,
    thumbnail: `/images/330px-Pascaline-CnAM_823-1-IMG_1506-black.jpg`,
    url: `https://en.wikipedia.org/wiki/Pascal%27s_calculator`,
  },
  "https://en.wikipedia.org/wiki/Jacquard_machine": {
    title: `Jacquard machine`,
    extract: `The Jacquard machine is a device fitted to a loom that simplifies the process of manufacturing textiles with such complex patterns as brocade, damask and matelassé. The resulting ensemble of the loom and Jacquard machine is then called a Jacquard loom. The machine was patented by Joseph Marie Jacquard in 1804, based on earlier inventions by the Frenchmen Basile Bouchon (1725), Jean Baptiste Falcon (1728), and Jacques Vaucanson (1740). The machine was controlled by a "chain of cards"; a number of punched cards laced together into a continuous sequence. Multiple rows of holes were punched on each card, with one complete card corresponding to one row of the design.`,
    thumbnail: `/images/330px-A_la_mémoire_de_J.M._Jacquard.jpg`,
    url: `https://en.wikipedia.org/wiki/Jacquard_machine`,
  },
  "https://en.wikipedia.org/wiki/Stephenson%27s_Rocket": {
    title: `Stephenson's Rocket`,
    extract: `Stephenson's Rocket is an early steam locomotive of 0-2-2 wheel arrangement. It was built for and won the Rainhill Trials of the Liverpool and Manchester Railway (L&MR), held in October 1829 to show that improved locomotives would be more efficient than stationary steam engines.`,
    thumbnail: `/images/330px-Stephenson's_Rocket_drawing.jpg`,
    url: `https://en.wikipedia.org/wiki/Stephenson%27s_Rocket`,
  },
  "https://en.wikipedia.org/wiki/What_hath_God_wrought": {
    title: `What hath God wrought`,
    extract: `"What hath God wrought" is a translation of a phrase from the Book of Numbers, and may refer to:"What hath God wrought", the official first Morse code message transmitted in the US on May 24, 1844, to officially open the Baltimore–Washington telegraph line
What Hath God Wrought? The History of the Salvation Army in Canada, a 1952 book by Arnold Brown
What Hath God Wrought: The Transformation of America, 1815–1848, a 2007 book by Daniel Walker Howe

`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/What_hath_God_wrought`,
  },
  "https://en.wikipedia.org/wiki/Frame-Breaking_Act": {
    title: `Destruction of Stocking Frames, etc. Act 1812`,
    extract: `The Destruction of Stocking Frames, etc. Act 1812, also known as the Frame-Breaking Act and before passage as the Frame Work Bill, was an act of the Parliament of the United Kingdom, passed by the British Government in 1812 aimed at increasing the penalties for Luddite behaviour in order to discourage it.`,
    thumbnail: `/images/330px-Coat_of_Arms_of_the_United_Kingdom_(1801-1816).svg.png`,
    url: `https://en.wikipedia.org/wiki/Frame-Breaking_Act`,
  },
  "https://en.wikipedia.org/wiki/Luddite": {
    title: `Luddite`,
    extract: `The Luddites were members of a 19th-century movement of English textile workers who opposed the use of certain types of automated machinery due to concerns relating to worker pay and output quality. They often destroyed the machines in organised raids. Members of the group referred to themselves as Luddites, self-described followers of "Ned Ludd", a legendary weaver whose name was used as a pseudonym in threatening letters to mill owners and government officials.`,
    thumbnail: `/images/330px-Luddite.jpg`,
    url: `https://en.wikipedia.org/wiki/Luddite`,
  },
  "https://en.wikipedia.org/wiki/Tabulating_machine": {
    title: `Tabulating machine`,
    extract: `The tabulating machine was an electromechanical machine designed to assist in summarizing information stored on punched cards. Invented by Herman Hollerith, the machine was developed to help process data for the 1890 U.S. Census. Later models were widely used for business applications such as accounting and inventory control. It spawned a class of machines, known as unit record equipment, and the data processing industry.`,
    thumbnail: `/images/330px-HollerithMachine.CHM.jpg`,
    url: `https://en.wikipedia.org/wiki/Tabulating_machine`,
  },
  "https://en.wikipedia.org/wiki/ENIAC": {
    title: `ENIAC`,
    extract: `ENIAC was the first programmable, electronic, general-purpose digital computer, completed in 1945. Other computers had some of these features, but ENIAC was the first to have them all. It was Turing-complete and able to solve "a large class of numerical problems" through reprogramming.`,
    thumbnail: `/images/330px-ENIAC_Penn1.jpg`,
    url: `https://en.wikipedia.org/wiki/ENIAC`,
  },
  "https://en.wikipedia.org/wiki/Soroban": {
    title: `Soroban`,
    extract: `The soroban  is an abacus developed in Japan. It is derived from the ancient Chinese suanpan, imported to Japan in the 14th century. Like the suanpan, the soroban is still used today, despite the proliferation of practical and affordable pocket electronic calculators.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/Soroban`,
  },
  "https://en.wikipedia.org/wiki/IBM_700/7000_series": {
    title: `IBM 700/7000 series`,
    extract: `The IBM 700/7000 series is a series of large-scale (mainframe) computer systems that were made by IBM through the 1950s and early 1960s. The series includes several different, incompatible processor architectures. The 700s use vacuum-tube logic and were made obsolete by the introduction of the transistorized 7000s. The 7000s, in turn, were eventually replaced with System/360, which was announced in 1964. However the 360/65, the first 360 powerful enough to replace 7000s, did not become available until November 1965. Early problems with OS/360 and the high cost of converting software kept many 7000s in service for years afterward.`,
    thumbnail: `/images/330px-IBM_Electronic_Data_Processing_Machine_-_GPN-2000-001881.jpg`,
    url: `https://en.wikipedia.org/wiki/IBM_700/7000_series`,
  },
  "https://en.wikipedia.org/wiki/Deep_Blue_versus_Garry_Kasparov": {
    title: `Deep Blue versus Garry Kasparov`,
    extract: `Garry Kasparov, then-world champion in chess, played a pair of six-game matches against Deep Blue, a supercomputer by IBM. Kasparov won the first match, held in Philadelphia in 1996, by 4–2. Deep Blue won a 1997 rematch held in New York City by 3½–2½. The second match was the first defeat of a reigning world chess champion by a computer under tournament conditions, and was the subject of a documentary film, Game Over: Kasparov and the Machine.`,
    thumbnail: `/images/330px-Deep_Blue.jpg`,
    url: `https://en.wikipedia.org/wiki/Deep_Blue_versus_Garry_Kasparov`,
  },
  "https://en.wikipedia.org/wiki/Pocket_calculator": {
    title: `Calculator`,
    extract: `A calculator is typically a portable electronic device used to perform calculations, ranging from basic arithmetic to complex mathematics.`,
    thumbnail: `/images/330px-Casio_calculator_JS-20WK_in_201901_002.jpg`,
    url: `https://en.wikipedia.org/wiki/Pocket_calculator`,
  },
  "https://en.wikipedia.org/wiki/Chinook_(computer_program)": {
    title: `Chinook (computer program)`,
    extract: `Chinook is a computer program that plays checkers. It was developed between the years 1989 to 2007 at the University of Alberta, by a team led by Jonathan Schaeffer and consisting of Rob Lake, Paul Lu, Martin Bryant, and Norman Treloar. The program's algorithms include an opening book which is a library of opening moves from games played by checkers grandmasters; a deep search algorithm; a good move evaluation function; and an end-game database for all positions with eight pieces or fewer. All of Chinook's knowledge was programmed by its creators, rather than learned using an artificial intelligence system.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/Chinook_(computer_program)`,
  },
  "https://en.wikipedia.org/wiki/CAPTCHA": {
    title: `CAPTCHA`,
    extract: `A CAPTCHA is a type of challenge–response Turing test used in computing to determine whether the user is human in order to deter bot attacks and spam.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/CAPTCHA`,
  },
  "https://en.wikipedia.org/wiki/Shazam_(music_app)": {
    title: `Shazam (music app)`,
    extract: `Shazam is a British application that can identify music based on a short sample played using the microphone on the device. It was created by the British company Shazam Entertainment, based in London, and has been owned by Apple since 2018. The software is available for Android, macOS, iOS, Wear OS, watchOS and as a Google Chrome extension.`,
    thumbnail: `/images/Shazam_interface_05-13-2018.png`,
    url: `https://en.wikipedia.org/wiki/Shazam_(music_app)`,
  },
  "https://en.wikipedia.org/wiki/Advanced_Chess": {
    title: `Advanced chess`,
    extract: `Advanced chess is a form of chess in which each human player uses a computer chess engine to explore the possible results of candidate moves. With this computer assistance, the human player controls and decides the game.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/Advanced_Chess`,
  },
  "https://en.wikipedia.org/wiki/DARPA_Grand_Challenge_(2004)": {
    title: `DARPA Grand Challenge (2004)`,
    extract: `Announced in 2002, the first DARPA Grand Challenge was a driverless car competition held on March 13, 2004 in the Mojave Desert region of the United States. The 150 miles (240 km) route followed Interstate 15 from right before Barstow, California to just past the California-Nevada border in Primm. None of the robot vehicles finished the route. The vehicle of Carnegie Mellon University's Red Team traveled the furthest distance, completing 11.78 km (7.32 mi) of the course. The \$1 million prize remained unclaimed.`,
    thumbnail: `/images/330px-DARPA_Challenge_RedTeam.jpg`,
    url: `https://en.wikipedia.org/wiki/DARPA_Grand_Challenge_(2004)`,
  },
  "https://en.wikipedia.org/wiki/Watson_(computer)": {
    title: `IBM Watson`,
    extract: `IBM Watson is a computer system capable of answering questions posed in natural language. It was developed as a part of IBM's DeepQA project by a research team, led by principal investigator David Ferrucci. Watson was named after IBM's founder and first CEO, industrialist Thomas J. Watson.`,
    thumbnail: `/images/330px-IBM_Watson.PNG`,
    url: `https://en.wikipedia.org/wiki/Watson_(computer)`,
  },
  "https://en.wikipedia.org/wiki/Google_Translate": {
    title: `Google Translate`,
    extract: `Google Translate is a multilingual neural machine translation service developed by Google to translate text, documents and websites from one language into another. It offers a website interface, a mobile app for Android and iOS, and an API that helps developers build browser extensions and software applications. As of March 2026, Google Translate supports 249 languages and language varieties at various levels. It served over 200 million people daily in May 2013, and over 500 million total users as of April 2016, with more than 100 billion words translated daily.`,
    thumbnail: `/images/330px-Google_Translate_screenshot.png`,
    url: `https://en.wikipedia.org/wiki/Google_Translate`,
  },
  "https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol": {
    title: `AlphaGo versus Lee Sedol`,
    extract: `AlphaGo versus Lee Sedol, also known as the DeepMind Challenge Match, was a five-game Go match between top Go player Lee Sedol and AlphaGo, a computer Go program developed by DeepMind, played in Seoul, South Korea between the 9th and 15th of March 2016. AlphaGo won all but the fourth game; all games were won by resignation. The match has been compared with the historic chess match between Deep Blue and Garry Kasparov in 1997.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/AlphaGo_versus_Lee_Sedol`,
  },
  "https://en.wikipedia.org/wiki/Stockfish_(chess)": {
    title: `Stockfish (chess)`,
    extract: `Stockfish is a free and open-source chess engine, available for various desktop and mobile platforms. It can be used in chess software through the Universal Chess Interface.`,
    thumbnail: `/images/330px-NewLogoSF.png`,
    url: `https://en.wikipedia.org/wiki/Stockfish_(chess)`,
  },
  "https://en.wikipedia.org/wiki/AlphaZero": {
    title: `AlphaZero`,
    extract: `AlphaZero is a computer program developed by artificial intelligence research company DeepMind to master the games of chess, shogi and go. This algorithm uses an approach similar to AlphaGo Zero.`,
    thumbnail: `/images/330px-Chess_Programming.svg.png`,
    url: `https://en.wikipedia.org/wiki/AlphaZero`,
  },
  "https://en.wikipedia.org/wiki/Residual_neural_network": {
    title: `Residual neural network`,
    extract: `A residual neural network is a deep learning architecture in which the layers learn residual functions with reference to the layer inputs. It was developed in 2015 for image recognition, and won the ImageNet Large Scale Visual Recognition Challenge of that year.`,
    thumbnail: `/images/330px-ResBlock.png`,
    url: `https://en.wikipedia.org/wiki/Residual_neural_network`,
  },
  "https://en.wikipedia.org/wiki/Libratus": {
    title: `Libratus`,
    extract: `Libratus is an artificial intelligence computer program designed to play poker, specifically heads up no-limit Texas hold 'em. Libratus' creators intend for it to be generalisable to other, non-poker-specific applications. It was developed at Carnegie Mellon University, Pittsburgh.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/Libratus`,
  },
  "https://en.wikipedia.org/wiki/Th%C3%A9%C3%A2tre_D%27op%C3%A9ra_Spatial": {
    title: `Théâtre D'opéra Spatial`,
    extract: `Théâtre D'opéra Spatial is a digital arts piece generated and edited by an American man named Jason M. Allen with the generative artificial intelligence (GAI) model Midjourney. It won the 2022 Colorado State Fair's annual fine art competition in the "emerging artist" (non-professional) division of the "Digital Arts/Digitally-Manipulated Photography" category on August 29, becoming one of the first images made using GAI to win such a prize. The award came with a \$300 cash prize.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/Th%C3%A9%C3%A2tre_D%27op%C3%A9ra_Spatial`,
  },
  "https://en.wikipedia.org/wiki/OpenAI_Five": {
    title: `OpenAI Five`,
    extract: `
OpenAI Five is a computer program by OpenAI that plays the five-on-five video game Dota 2. Its first public appearance occurred in 2017, where it was demonstrated in a live one-on-one game against the professional player Dendi, who lost to it. The following year, the system had advanced to the point of performing as a full team of five, and began playing against and showing the capability to defeat professional teams.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/OpenAI_Five`,
  },
  "https://en.wikipedia.org/wiki/AlphaStar_(software)": {
    title: `AlphaStar (software)`,
    extract: `AlphaStar is an artificial intelligence (AI) software developed by DeepMind for playing the video game StarCraft II. It was unveiled to the public by name in January 2019. AlphaStar attained "Grandmaster" status in August 2019, considered a milestone for AI in video games at the time.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/AlphaStar_(software)`,
  },
  "https://en.wikipedia.org/wiki/GPT-3": {
    title: `GPT-3`,
    extract: `Generative Pre-trained Transformer 3 (GPT-3) is a large language model released by OpenAI in 2020.`,
    thumbnail: `/images/330px-OpenAI_logo_2025_(symbol).svg.png`,
    url: `https://en.wikipedia.org/wiki/GPT-3`,
  },
  "https://en.wikipedia.org/wiki/ChatGPT": {
    title: `ChatGPT`,
    extract: `ChatGPT is a generative artificial intelligence chatbot developed by OpenAI. It was released in November 2022. It uses generative pre-trained transformers (GPTs), such as GPT-5.2, to generate text, speech, and images in response to user prompts. It is credited with accelerating the AI boom, an ongoing period marked by rapid investment and public attention toward the field of artificial intelligence (AI). OpenAI operates the service on a freemium model. Users can interact with ChatGPT through text, audio, and image prompts.`,
    thumbnail: `/images/330px-OpenAI_logo_2025_(symbol).svg.png`,
    url: `https://en.wikipedia.org/wiki/ChatGPT`,
  },
  "https://en.wikipedia.org/wiki/GPT-4": {
    title: `GPT-4`,
    extract: `Generative Pre-trained Transformer 4 (GPT-4) is a large language model developed by OpenAI and the fourth in its series of GPT foundation models.`,
    thumbnail: `/images/GPT-4_icon.png`,
    url: `https://en.wikipedia.org/wiki/GPT-4`,
  },
  "https://en.wikipedia.org/wiki/Mata_v._Avianca,_Inc.": {
    title: `Mata v. Avianca, Inc.`,
    extract: `Mata v. Avianca, Inc. was a U.S. District Court for the Southern District of New York case in which the Court dismissed a personal injury case against the airline Avianca and issued a \$5,000 fine to the plaintiffs' lawyers who had submitted fake precedents generated by ChatGPT in their legal briefs.`,
    thumbnail: `/images/330px-USDCSDNY.svg.png`,
    url: `https://en.wikipedia.org/wiki/Mata_v._Avianca,_Inc.`,
  },
  "https://en.wikipedia.org/wiki/2023_Writers_Guild_of_America_strike": {
    title: `2023 Writers Guild of America strike`,
    extract: `From May 2 to September 27, 2023, the Writers Guild of America (WGA)—representing 11,500 screenwriters—went on strike over a labor dispute with the Alliance of Motion Picture and Television Producers (AMPTP). Lasting 148 days, the strike is tied with the 1960 strike as the second-longest labor stoppage actioned by the WGA, only behind the 1988 strike. Alongside the 2023 SAG-AFTRA strike, which lasted between July and November, it was part of a series of broader Hollywood labor disputes. Both strikes contributed to the biggest interruption to the American film and television industries since the COVID-19 pandemic.`,
    thumbnail: `/images/330px-We_are_not_in_severance.jpg`,
    url: `https://en.wikipedia.org/wiki/2023_Writers_Guild_of_America_strike`,
  },
  "https://en.wikipedia.org/wiki/Riffusion": {
    title: `Riffusion`,
    extract: `Riffusion is a neural network, designed by Seth Forsgren and Hayk Martiros, that generates music using images of sound rather than audio.`,
    thumbnail: `/images/330px-AI-generated_audio_featuring_bossa_nova_music_with_electric_guitar.png`,
    url: `https://en.wikipedia.org/wiki/Riffusion`,
  },
  "https://en.wikipedia.org/wiki/AlphaFold": {
    title: `AlphaFold`,
    extract: `AlphaFold is an artificial intelligence (AI) program developed by DeepMind, a subsidiary of Alphabet, which performs predictions of protein structure. It is designed using deep learning techniques.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/AlphaFold`,
  },
  "https://en.wikipedia.org/wiki/Geoffrey_Hinton": {
    title: `Geoffrey Hinton`,
    extract: `Geoffrey Everest Hinton is a British-Canadian computer scientist, cognitive scientist, cognitive psychologist and Nobel Prize laureate known for his work on artificial neural networks, which earned him the title "the Godfather of AI". He is University Professor Emeritus at the University of Toronto.`,
    thumbnail: `/images/330px-Geoffrey_E._Hinton,_2024_Nobel_Prize_Laureate_in_Physics_(cropped1).jpg`,
    url: `https://en.wikipedia.org/wiki/Geoffrey_Hinton`,
  },
  "https://en.wikipedia.org/wiki/Artificial_Intelligence_Act": {
    title: `Artificial Intelligence Act`,
    extract: `The Artificial Intelligence Act is a European Union regulation concerning artificial intelligence (AI). It establishes a common regulatory and legal framework for AI within the European Union (EU). The regulation entered into force on 1 August 2024, with provisions that shall come into operation gradually over the following 6 to 36 months.`,
    thumbnail: `/images/330px-Flag_of_Europe.svg.png`,
    url: `https://en.wikipedia.org/wiki/Artificial_Intelligence_Act`,
  },
  "https://en.wikipedia.org/wiki/AI_Safety_Summit": {
    title: `AI Safety Summit 2023`,
    extract: `The AI Safety Summit 2023 was an international conference on the safety and regulation of artificial intelligence. Organized by the British government, it was held in November 2023 at Bletchley Park, Milton Keynes, England.`,
    thumbnail: `/images/330px-Bletchley_Park_Mansion.jpg`,
    url: `https://en.wikipedia.org/wiki/AI_Safety_Summit`,
  },
  "https://en.wikipedia.org/wiki/AI_agent": {
    title: `AI agent`,
    extract: `In the context of generative artificial intelligence, AI agents are a class of intelligent agents distinguished by their ability to operate autonomously in complex environments. Agentic AI tools prioritize decision-making over content creation and do not require continuous oversight.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/AI_agent`,
  },
  "https://en.wikipedia.org/wiki/2024_Nobel_Prizes": {
    title: `2024 Nobel Prizes`,
    extract: `
The 2024 Nobel Prizes were awarded by the Nobel Foundation, based in Sweden. Six categories were awarded: Physics, Chemistry, Physiology or Medicine, Literature, Peace, and Economic Sciences. The winners in each category were announced from October 7 to October 14.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/2024_Nobel_Prizes`,
  },
  "https://en.wikipedia.org/wiki/GitHub_Copilot": {
    title: `GitHub Copilot`,
    extract: `GitHub Copilot is a code completion and programming AI-assistant developed by GitHub and OpenAI that assists users of Visual Studio Code, Visual Studio, Neovim, Eclipse and JetBrains integrated development environments (IDEs) by autocompleting code. Currently available by subscription to individual developers and to businesses, the generative artificial intelligence software was first announced by GitHub on 29 June 2021. Users can choose the large language model used for generation.`,
    thumbnail: undefined,
    url: `https://en.wikipedia.org/wiki/GitHub_Copilot`,
  },
};
